esphome:
  name: kiosk-living-room
  friendly_name: Kiosk Living Room
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

psram:
  mode: octal
  speed: 120MHz

esp32:
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "something"

ota:
  - platform: esphome
    password: "something"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kiosk-Living-Room"
    password: "something"

captive_portal:
# Packages - Using local files (relative to esphome.yaml location)
packages:
  setup:
    url: https://github.com/dgshue/LivingRoom-Kiosk/
    files: [LivingRoom-Kiosk/device/device.yaml,
            LivingRoom-Kiosk/device/sensors.yaml,
            LivingRoom-Kiosk/device/lvgl.yaml,
            LivingRoom-Kiosk/addon/time.yaml,
            LivingRoom-Kiosk/addon/backlight.yaml,
            LivingRoom-Kiosk/addon/network.yaml,
            LivingRoom-Kiosk/assets/fonts.yaml,
            LivingRoom-Kiosk/assets/icons.yaml,
            LivingRoom-Kiosk/theme/button.yaml]
    refresh: 1sec