# ESP32-S3-Touch-LCD-7
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"
  room: "Your Room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-lvgl/
    files: [waveshare-esp32-s3-touch-lcd-7/device/device.yaml,
            waveshare-esp32-s3-touch-lcd-7/device/sensors.yaml,
            waveshare-esp32-s3-touch-lcd-7/device/lvgl.yaml,
            waveshare-esp32-s3-touch-lcd-7/addon/time.yaml,
            waveshare-esp32-s3-touch-lcd-7/addon/backlight.yaml,
            waveshare-esp32-s3-touch-lcd-7/addon/network.yaml,
            waveshare-esp32-s3-touch-lcd-7/assets/fonts.yaml,
            waveshare-esp32-s3-touch-lcd-7/assets/icons.yaml,
            waveshare-esp32-s3-touch-lcd-7/theme/button.yaml]
    refresh: 1sec
